# Creating a heatmap

In [1]:
import numpy as np
import pandas as pd

In [2]:
athletes = pd.read_excel('../data/athletes.xlsx')
athletes.head()

    rcc  wcc    hc    hg  ferr    bmi    ssf  pcBfat    lbm     ht    wt
0  3.96  7.5  37.5  12.3    60  20.56  109.1   19.75  63.32  195.9  78.9
1  4.41  8.3  38.2  12.7    68  20.67  102.8   21.30  58.55  189.7  74.4
2  4.14  5.0  36.4  11.6    21  21.86  104.6   19.88  55.36  177.8  69.1
3  4.11  5.3  37.3  12.6    69  21.88  126.4   23.66  57.18  185.0  74.9
4  4.45  6.8  41.5  14.0    29  18.96   80.3   17.64  53.20  184.6  64.6

## Heatmap

In [13]:
athletes_corr = (
    athletes
    .corr()
    .round(2)
    .replace(1,'')
)

athletes_corr

         rcc   wcc    hc    hg  ferr   bmi   ssf pcBfat   lbm    ht    wt
rcc           0.15  0.92  0.89  0.25   0.3  -0.4  -0.49  0.55  0.36   0.4
wcc     0.15        0.15  0.13  0.13  0.18  0.14   0.11   0.1  0.08  0.16
hc      0.92  0.15        0.95  0.26  0.32 -0.45  -0.53  0.58  0.37  0.42
hg      0.89  0.13  0.95        0.31  0.38 -0.44  -0.53  0.61  0.35  0.46
ferr    0.25  0.13  0.26  0.31         0.3 -0.11  -0.18  0.32  0.12  0.27
bmi      0.3  0.18  0.32  0.38   0.3        0.32   0.19  0.71  0.34  0.85
ssf     -0.4  0.14 -0.45 -0.44 -0.11  0.32         0.96 -0.21 -0.07  0.15
pcBfat -0.49  0.11 -0.53 -0.53 -0.18  0.19  0.96        -0.36 -0.19  -0.0
lbm     0.55   0.1  0.58  0.61  0.32  0.71 -0.21  -0.36         0.8  0.93
ht      0.36  0.08  0.37  0.35  0.12  0.34 -0.07  -0.19   0.8        0.78
wt       0.4  0.16  0.42  0.46  0.27  0.85  0.15   -0.0  0.93  0.78

Total rows and columns in correlation matrix.

In [17]:
first_row=1
first_col=1

(last_row, last_col) = athletes_corr.shape

display(first_row, first_col, last_row, last_col)

1

1

11

11

## Create Excel

In [24]:
## Set pandas engine to xlsxwriter
writer = pd.ExcelWriter('../output/13_correlation.xlsx', engine = 'xlsxwriter')

## Convert DF to xlsxwriter object
athletes_corr.to_excel(writer, index = True)

## Create workbook and worksheet
workbook = writer.book
worksheet = writer.sheets['Sheet1']

## Conditional formatting

worksheet.conditional_format(first_row, first_col, last_row, last_col,
                            {'type':'3_color_scale'})


workbook.close()